#!/usr/bin/env python3
"""
backfill_irrational.py — Patch existing DB CMFs with irrational fields
from store_*.jsonl records that were generated by irrational_scout.py.

Also exports data/irrational_candidates.json with all looks_irrational CMFs.
"""
import json, sqlite3
from pathlib import Path

HERE   = Path(__file__).parent
GAUGE  = HERE / "gauge_agents"
DB     = HERE / "data" / "atlas_2d.db"
OUT    = HERE / "data" / "irrational_candidates.json"


def main():
    print("Loading store files …")
    # Build fp → irrational info map from all store files
    fp_map: dict[str, dict] = {}
    for sf in sorted(GAUGE.glob("store_*.jsonl")):
        for line in sf.read_text(errors="replace").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except Exception:
                continue
            fp = (rec.get("fingerprint") or "")[:16]
            if not fp:
                continue
            # Only process records that have irrational info
            if rec.get("looks_irrational") or rec.get("limit_label"):
                fp_map[fp] = {
                    "looks_irrational": bool(rec.get("looks_irrational", False)),
                    "irrational_type":  rec.get("irrational_type"),
                    "limit_label":      rec.get("limit_label"),
                    "limit_value":      rec.get("limit_value"),
                    "scout_batch":      rec.get("scout_batch"),
                }

    print(f"  Store records with irrational info: {len(fp_map)}")

    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    cur = con.cursor()

    # Fetch all gauge_agent CMFs
    rows = cur.execute("""
        SELECT c.id, r.canonical_fingerprint, c.cmf_payload
        FROM cmf c
        JOIN representation r ON c.representation_id = r.id
        WHERE r.primary_group = 'gauge_agent'
    """).fetchall()

    updated = 0
    for row in rows:
        fp = (row["canonical_fingerprint"] or "")[:16]
        info = fp_map.get(fp)
        if not info:
            continue
        try:
            payload = json.loads(row["cmf_payload"])
        except Exception:
            continue
        payload["looks_irrational"] = info["looks_irrational"]
        payload["irrational_type"]  = info["irrational_type"]
        payload["limit_label"]      = info["limit_label"]
        payload["limit_value"]      = info["limit_value"]
        if info.get("scout_batch"):
            payload["scout_batch"]  = info["scout_batch"]
        cur.execute("UPDATE cmf SET cmf_payload = ? WHERE id = ?",
                    (json.dumps(payload), row["id"]))
        updated += 1

    con.commit()
    print(f"  Updated {updated} CMFs in DB.")

    # Export irrational candidates to JSON
    irr_rows = cur.execute("""
        SELECT c.id, c.dimension, c.category, c.cmf_payload,
               r.canonical_fingerprint, r.canonical_payload
        FROM cmf c
        JOIN representation r ON c.representation_id = r.id
        WHERE json_extract(c.cmf_payload,'$.looks_irrational') = 1
        ORDER BY c.id
    """).fetchall()

    candidates = []
    for row in irr_rows:
        try:
            payload      = json.loads(row["cmf_payload"])
            canon        = json.loads(row["canonical_payload"])
        except Exception:
            continue
        candidates.append({
            "id":              row["id"],
            "dimension":       row["dimension"],
            "category":        row["category"],
            "fingerprint":     row["canonical_fingerprint"],
            "agent_type":      payload.get("agent_type"),
            "matrix_size":     payload.get("matrix_size"),
            "best_delta":      payload.get("best_delta"),
            "looks_irrational":payload.get("looks_irrational"),
            "irrational_type": payload.get("irrational_type"),
            "limit_label":     payload.get("limit_label"),
            "limit_value":     payload.get("limit_value"),
            "axes":            canon.get("axes"),
            "matrices":        canon.get("matrices"),
            "source_category": payload.get("source_category"),
            "certification_level": payload.get("certification_level"),
        })

    con.close()

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(candidates, indent=2))
    print(f"  Exported {len(candidates)} irrational candidates → {OUT}")


if __name__ == "__main__":
    main()
